name: Request
on:
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created
env:
  TZ: 'Asia/Tokyo'
defaults:
  run:
    working-directory: ./bench
jobs:
  register:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      issues: write
    if: |
      contains(github.event.issue.labels.*.name, 'registration') && (
        (github.event_name == 'issues') || (
          github.event_name == 'issue_comment' &&
          !github.event.issue.pull_request &&
          startsWith(github.event.comment.body, '/retry') &&
          (github.actor == github.event.issue.user.login)
        )
      )
    steps:
      - if: github.event_name == 'issues'
        run: |
          gh api -X POST repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/reactions -f content=+1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: github.event_name == 'issue_comment'
        run: |
          gh api -X POST repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions -f content=+1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-murray/issue-forms-body-parser@22e5d90e6a607073d08891bc036461971cbcfb45 # renovate: tag=v4.2.1
        id: issue-parsed
        with:
          issue_id: ${{ github.event.issue.number }}
          label_marker_start: '{{'
          label_marker_end: '}}'
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # renovate: tag=v4.2.2
        with:
          fetch-depth: 0
      - run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          mise install
        env:
          MISE_VERSION: '2025.3.2'
      - run: |
          pnpm install --frozen-lockfile
      - run: |
          pnpm start --applicationUrl ${TARGET_URL}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: 'Asia/Tokyo'
          TARGET_URL: ${{ fromJSON(steps.issue-parsed.outputs.payload).url }}
